//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_POS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Potrawa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Potrawa()
        {
            this.Obejmuje = new HashSet<Obejmuje>();
            this.Zawiera = new HashSet<Zawiera>();
        }
    
        public decimal id_potrawy { get; set; }
        public string nazwa_potrawy { get; set; }
        public Nullable<decimal> gramatura_potrawy { get; set; }
        public Nullable<decimal> cena_potrawy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Obejmuje> Obejmuje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zawiera> Zawiera { get; set; }
    }
}
