//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_POS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skladnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Skladnik()
        {
            this.Zawiera = new HashSet<Zawiera>();
        }
    
        public string id_skladnika { get; set; }
        public string nazwa_skladnika { get; set; }
        public Nullable<decimal> cena_za_kg { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zawiera> Zawiera { get; set; }
    }
}
