//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_POS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uzytkownik
    {
        public decimal id_uzytkownika { get; set; }
        public string nazwa_uzytkownika { get; set; }
        public string haslo { get; set; }
        public string typ_uzytkownika { get; set; }
    }
}
