//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_POS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zawiera
    {
        public decimal id_potrawy { get; set; }
        public string id_skladnika { get; set; }
        public Nullable<decimal> ile_skladnika { get; set; }
    
        public virtual Potrawa Potrawa { get; set; }
        public virtual Skladnik Skladnik { get; set; }
    }
}
